tact_factory_web_service:
    resource: "@TactFactoryWebServiceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_bundle:
   resource: "@TactFactoryWebServiceBundle/Resources/config/routing.yml"