admin_admin_bundle_sonata_admin:
    resource: "@AdminAdminBundleSonataAdminBundle/Controller/"
    type:     annotation
    prefix:   /


tact_factory_web_service:
    resource: "@TactFactoryWebServiceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FOS_USER    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_bundle:
   resource: "@TactFactoryWebServiceBundle/Resources/config/routing.yml"

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

  #SONATA_ADMIN
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin