<?php

namespace TactFactory\WebServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MCQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MCQRepository extends EntityRepository
{
}
