<?php

namespace TactFactory\WebServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypRepository extends EntityRepository
{
}
